### ISSUE TITLE
Specify test cases with identified commit SHAs

### ISSUE THREAD

**Issue by Anirban166** [DorisAmoakohene/Efficiency-and-Performance-Test.RData.table#5]
Can you please classify which test cases here in your repository (among 1 to 12 that I see as per the readme) are currently working and include the three (Before, Regression, Fix) commit IDs?

(Also, the links to some of them in the readme are broken or redirect to the repository itself at present)

**Comment by DorisAmoakohene** [comment]
I have now 
The links will be working 
Try again

**Comment by DorisAmoakohene** [comment]
The first four on my page https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/main/README.md everything is working @Anirban166

**Comment by Anirban166** [comment]
> The first four on my page https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/main/README.md everything is working @Anirban166

Since some of them (such as [this one](atime.list2 <- atime::atime_versions() and [that one](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/dc26ba45a392812413c87574aa5804a7ef98d88c/Remove%20deep%20copy%20of%20indices%20from%20shallow.Rmd#L33)) are not working when we place the same arguments as used in `atime::versions` inside of a `test.list` to pass to `atime::atime_pkg`, can you try to make them work using `atime_pkg` locally for you?

**Comment by Anirban166** [comment]
> The first four on my page https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/main/README.md everything is working @Anirban166

Since some of them (such as [this one](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/dc26ba45a392812413c87574aa5804a7ef98d88c/Performance%20regression%20with%235424.Rmd#L97) and [that one](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/dc26ba45a392812413c87574aa5804a7ef98d88c/Remove%20deep%20copy%20of%20indices%20from%20shallow.Rmd#L33)) are not working when we place the same arguments as used in `atime::versions` inside of a `test.list` to pass to `atime::atime_pkg`, can you try to make them work using `atime_pkg` locally for you?

**Comment by Anirban166** [comment]
(Closing this since I solved it earlier)
