### ISSUE TITLE
Use of the wrong commit ID for 'Before' in the third example case here, have all examples in one place/repository, and add to your comments why a commit is used for 'Before'/'Regression'/'After'

### ISSUE THREAD

**Issue by Anirban166** [DorisAmoakohene/Efficiency-and-Performance-Test.RData.table#6]
For case [3](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table?tab=readme-ov-file#3), the commits used for 'Before' and 'Regression' here ([source](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/main/Remove%20deep%20copy%20of%20indices%20from%20shallow.Rmd#L77)) aren't making sense if we were to see the order they are in `data.table` history:

```r
  "Before"="ad7b67c80a551b7a1e2ef8b73d6162ed7737c934",
#https://github.com/Rdatatable/data.table/commit/ad7b67c80a551b7a1e2ef8b73d6162ed7737c934
  "Regression"="752012f577f8e268bb6d0084ca39a09fa7fbc1c4", 
#https://github.com/Rdatatable/data.table/tree/752012f577f8e268bb6d0084ca39a09fa7fbc1c4
  "Fixed"="9d3b9202fddb980345025a4f6ac451ed26a423be")#https://github.com/Rdatatable/data.table/commit/9d3b9202fddb980345025a4f6ac451ed26a423be 
```

<img width="1614" alt="image" src="https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/assets/30123691/8d536806-ca18-44a3-bcd9-34f83ea164f4">

(The commit associated with 'Regression' or the one that introduced/has the regression cannot predate the commit associated with 'Before' as that should always be *before* the regression happened) 

I see that there are different commit SHAs ([source](https://github.com/DorisAmoakohene/PerformanceTest_data.table/blob/bfc7e08399b8fab9f980bf28a8b5aa60c919ac42/Working%20Examples/PR%204440/Remove%20deep%20copy%20of%20indices%20from%20shallow.Rmd#L77)) you are using in your new repository, but then the information here (which I followed previously) would be redundant right?

I would suggest you to update the readme here to redirect to your [new repository](https://github.com/DorisAmoakohene/PerformanceTest_data.table) and have everything similar in one place/repo only to avoid confusion (and also potential misinformation like this case here).

Also, can you please add some detail as to why you used those commits on your comments apart from providing the links? (I don't see it in the new repository but I just saw that @tdhock already created an [issue](https://github.com/DorisAmoakohene/PerformanceTest_data.table/issues/4) for that)

For the two test cases that I'll be pushing to the `data.table` repository (one of which is the same one we're discussing above), I don't see such comments so I wrote based on what I saw/understood. For example, here's what I currently have:
- For the performance regression that got fixed in #4440: (or case 3 in your repository here)
```r
    "Before" = "9d3b9202fddb980345025a4f6ac451ed26a423be", # This should be changed later. Currently, the source of regression (or the particular commit that led to it) is not clear. In addition, older versions of data.table are having problems when being installed in this manner. (This includes commits from before Mar 20, 2020 or when the issue that discovered or first mentioned the regression was created)
    "Regression" = "752012f577f8e268bb6d0084ca39a09fa7fbc1c4", # A commit that is affected by the regression: https://github.com/Rdatatable/data.table/commit/752012f577f8e268bb6d0084ca39a09fa7fbc1c4
    "Fixed" = "9d3b9202fddb980345025a4f6ac451ed26a423be"), # The merge commit in #4440, the PR that fixed the regression: https://github.com/Rdatatable/data.table/commit/9d3b9202fddb980345025a4f6ac451ed26a423be
```
- For the performance regression that got fixed in #5463: (or case 1 in your repository here)
```r
    "Before" = "be2f72e6f5c90622fe72e1c315ca05769a9dc854", # The commit in PR #4491 that comes before the regression introducting commit: https://github.com/Rdatatable/data.table/pull/4491/commits/be2f72e6f5c90622fe72e1c315ca05769a9dc854
    "Regression" = "e793f53466d99f86e70fc2611b708ae8c601a451", # The commit in #4491 that introduced the regression: https://github.com/Rdatatable/data.table/pull/4491/commits/e793f53466d99f86e70fc2611b708ae8c601a451
    "Fixed" = "58409197426ced4714af842650b0cc3b9e2cb842") # Last commit in #5463, the PR that fixed the regression: https://github.com/Rdatatable/data.table/pull/5463/commits/58409197426ced4714af842650b0cc3b9e2cb842   
```

**Comment by DorisAmoakohene** [comment]
Hi @Anirban166, I mentioned last week I change or updated these content to a new repo, I have addressed all these already in this repository 
https://github.com/DorisAmoakohene/PerformanceTest_data.table

Kindly visit this repo and let me know if you still need anymore clarification

**Comment by Anirban166** [comment]
Hello Doris, I don't see anything in the readme here in [this repository](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table) to redirect to the new one (and as I'm seeing here, this been last updated a month ago?)

Please edit the readme here to redirect to your new repository there - Mention that at the top preferably so people can notice, and I'd suggest to remove all the information there and just mention this redirection if you intend to replace this repository's purpose with the new one. It's confusing to have information spread out like this in two places.

> https://github.com/DorisAmoakohene/PerformanceTest_data.table

I read the [readme](https://github.com/DorisAmoakohene/PerformanceTest_data.table/blob/master/README.md) of that new repository (and it's good that you outlined the structure of that repository) but I don't see any information that indicates that the [older one](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/main/README.md) should not be followed and instead this should be referred to only (make it one concrete source of information).

**Comment by Anirban166** [comment]
Hello Doris, I don't see anything in the readme *here* or in [this repository](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table) to redirect to the new one (and as I'm seeing here, this been last updated a month ago?)

Please edit the readme here to redirect to your new repository there - Mention that at the top preferably so people can notice, and I'd suggest to remove all the information there and just mention this redirection if you intend to replace this repository's purpose with the new one. It's confusing to have information spread out like this in two places.

> https://github.com/DorisAmoakohene/PerformanceTest_data.table

I read the [readme](https://github.com/DorisAmoakohene/PerformanceTest_data.table/blob/master/README.md) of that new repository (and it's good that you outlined the structure of that repository) but I don't see any information that indicates that the [older one](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/main/README.md) should not be followed and instead this should be referred to only (make it one concrete source of information).

**Comment by Anirban166** [comment]
Hello Doris, I don't see anything in the readme *here* or in [this repository](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table) to redirect to the new one (and as I'm seeing here, this been last updated a month ago?)

Please edit the readme here to redirect to your new repository there - Mention that at the top preferably so people can notice, and I'd suggest to remove all the information here and just mention this redirection if you intend to replace this repository's purpose with the new one. Carry over what you need to from here and have it explained there in detail. It's confusing to have information spread out like this in two places.

> https://github.com/DorisAmoakohene/PerformanceTest_data.table

I read the [readme](https://github.com/DorisAmoakohene/PerformanceTest_data.table/blob/master/README.md) of that new repository (and it's good that you outlined the structure of that repository) but I don't see any information that indicates that the [older one](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/main/README.md) should not be followed and instead this should be referred to only (make it one concrete source of information).

**Comment by Anirban166** [comment]
Just saw the changes to the readme in this repository - Great!
